### ISSUE TITLE
Numeric values in queries are not correctly mapped

### ISSUE THREAD

**Issue by ryanaip** [sdl/odata-jpa-datasource#1]
When running a query against my data source, like `http://localhost:8080/jpa.svc/Customers?$format=json&$filter=id eq 011895`, I get the following error:

`java.lang.IllegalArgumentException: Parameter value [11895] did not match expected type [java.lang.Integer (n/a)]`

The parameter being passed in [JPADatasourceProvider](https://github.com/sdl/odata-jpa-datasource/blob/master/odata-jpa/src/main/java/com/sdl/odata/datasource/jpa/JPADatasourceProvider.java#L150) is of type `scala.math.BigDecimal` even though my annotated JPA column is of type Integer.

Any thoughts on why this is happening or how to fix it?  Is there a way I can update the data type through additional annotations?

**Comment by ppete78** [comment]
I had the same issue. Any resolution?

**Comment by renarj** [comment]
I have created a quick fix for this, I had not checked it in because I do not like the fix (see #3 ). But i simply do not have the time to look for a proper fix due to other priorities. Should be solved on the master branch now.
